// Generated by CoffeeScript 2.4.1
(function() {
  var patterns;

  patterns = {
    comma: /\,/,
    space: /\s/,
    letter: /[a-zA-Zа-яА-Я]/,
    anySym: /[\!\@\#\$\%\^\&\*\(\)\=\_\`\~\'\\\|\/\+\:\;\>\<\?]/,
    point: /\./g,
    hyphen: /\-/,
    number: /\D/
  };

  document.ElementsExists = false;

  document.inputCache = '';

  String.prototype.replaceAll = function(search, replace) {
    return this.split(search).join(replace);
  };

  $(document).ready(function() {
    var url;
    $('[data-toggle="tooltip"]').tooltip();
    $('[data-toggle="popover"]').popover();
    url = document.location.toString();
    if (url.match('#')) {
      return $('.nav-pills a[href="#' + url.split('#')[1] + '"]').tab('show');
    }
  });

  $('.nav-pills a').on('shown.bs.tab', function(event) {
    return window.location.hash = event.target.hash;
  });

  //Валідація поля типу decimal
  $(document).on('focus', '[data-inspect]', function() {
    return document.inputCache = $(this).val();
  });

  $(document).on('focusout', '[data-inspect]', function() {
    return document.inputCache = '';
  });

  $(document).on('keyup', '[data-inspect="decimal"]', function() {
    var pointCounter, split, value;
    value = $(this).val();
    if (value === '') {
      return;
    }
    value = value.replaceAll(patterns.comma, '.');
    value = value.replaceAll(patterns.space, '');
    value = value.replaceAll(patterns.letter, '');
    value = value.replaceAll(patterns.anySym, '.');
    pointCounter = value.match(patterns.point) === null ? 0 : value.match(patterns.point).length;
    if (pointCounter === 1) {
      split = value.split('.', 2);
      if (split[1].length > 2) {
        value = document.inputCache;
      }
    } else if (pointCounter > 1) {
      value = document.inputCache;
    }
    document.inputCache = value;
    return $(this).val(value);
  });

  $(document).on('keyup', '[data-inspect="integer"]', function() {
    var minus, value;
    value = $(this).val();
    if (value === '') {
      return;
    }
    minus = value.match(patterns.hyphen);
    value = value.replaceAll(patterns.number, '');
    if (minus) {
      value = `-${value}`;
    }
    return $(this).val(value);
  });

  $(document).on('submit', '[data-type="ajax"]', function(event) {
    var data, redirectTo, send, success, url;
    event.preventDefault();
    data = $(this).serializeJSON();
    url = $(this).attr('action');
    redirectTo = $(this).data('redirect-to');
    success = $(this).data('success');
    if (document.ElementsExists) {
      data = Elements.customFormSerializePush(data, this);
    }
    $(this).find('button').attr('disabled', true);
    send = function() {
      return $.ajax({
        type: 'post',
        url: url,
        data: data,
        success: answer(() => {
          success = (function() {
            switch (false) {
              case !'redirect':
                return successHandler(answer, function() {
                  return location.href = redirectTo;
                });
              case !'close':
                return successHandler(answer, true);
              default:
                return successHandler(answer);
            }
          })();
          return $(this).find('button').attr('disabled', false);
        }),
        error: answer(() => {
          errorHandler(answer);
          return $(this).find('button').attr('disabled', false);
        })
      });
    };
    if ($(this).data('pin_code') != null) {
      return pin_code(function() {
        return send;
      });
    } else {
      return send;
    }
  });

  $(document).on('click', '[data-type="delete"]', function(event) {
    var action, data, id, url;
    event.preventDefault();
    id = $(this).data('id');
    url = $(this).data('uri');
    action = $(this).data('action');
    data = $(this).data('post');
    data = data !== void 0 ? `${data}&action=${action}` : {id, action};
    return delete_on_click(function() {
      return $.ajax({
        type: 'post',
        url: url,
        data: data,
        success: function(answer) {
          return successHandler(answer);
        },
        error: function(answer) {
          return errorHandler(answer);
        }
      });
    });
  });

  $(document).on('click', '[data-type="get_form"]', function(event) {
    var action, data, post, url;
    event.preventDefault();
    url = $(this).data('uri');
    action = $(this).data('action');
    post = $(this).data('post');
    data = post === void 0 ? `action=${action}` : `${post}&action=${action}`;
    $(this).attr('disabled', true);
    return $.ajax({
      type: 'post',
      url: url,
      data: data,
      success: function(answer) {
        myModalOpen(answer);
        return $(this).attr('disabled', false);
      },
      error: function(answer) {
        errorHandler(answer);
        return $(this).attr('disabled', false);
      }
    });
  });

  $(document).on('click', '[data-type="ajax_request"]', function(event) {
    var action, data, url;
    event.preventDefault();
    url = $(this).data('uri');
    data = $(this).data('post');
    action = $(this).data('action');
    data = `${data}&action=${action}`;
    return $.ajax({
      type: 'post',
      url: url,
      data: data,
      success: function(answer) {
        return successHandler(answer);
      },
      error: function(answer) {
        return errorHandler(answer);
      }
    });
  });

  $(document).on('click', '#map-signs', function(event) {
    var content, left_bar;
    event.preventDefault();
    left_bar = $('#left_bar');
    content = $('#content');
    if (left_bar.hasClass('mini-bar')) {
      left_bar.toggleClass('navigation', true);
      left_bar.toggleClass('mini-bar', false);
      $.cookie('left_bar_template_class', 'navigation', {
        expires: 5
      });
    } else {
      left_bar.toggleClass('navigation', false);
      left_bar.toggleClass('mini-bar', true);
      $.cookie('left_bar_template_class', 'mini-bar', {
        expires: 5
      });
    }
    if (content.hasClass('content-mini')) {
      content.toggleClass('content-big', true);
      content.toggleClass('content-mini', false);
      return $.cookie('content_template_class', 'content-big', {
        expires: 5
      });
    } else {
      content.toggleClass('content-big', false);
      content.toggleClass('content-mini', true);
      return $.cookie('content_template_class', 'content-mini', {
        expires: 5
      });
    }
  });

  $(document).on('hide.bs.modal', '.modal', function() {
    return $(this).remove();
  });

  $('a[data-type="pin_code"]').on('click', function() {
    var href;
    href = $(this).data('href');
    return pin_code(function() {
      return window.location.href = href;
    });
  });

  window.str_to_int = function(str) {
    return str.replace(/\D+/g, "");
  };

  window.getParameters = function() {
    var Pattern, params;
    Pattern = /[\?][\w\W]+/;
    params = document.location.href.match(Pattern);
    if (params != null) {
      return params = '';
    }
  };

  window.log = function(type, desc) {
    return $.ajax({
      type: 'post',
      url: '/log',
      data: {type, desc}
    });
  };

  window.elog = function(desc) {
    return log('error_in_javascript_file', desc);
  };

  window.redirect = function(url) {
    return window.location.href = url;
  };

  window.url = function(path) {
    path = path.replace(/^\//, '');
    return `${my_url}/${path}`;
  };

  window.autoComplete = function(url, field, selectCallback) {
    return $(field).autocomplete({
      source: function(request, response) {
        return $.ajax({
          type: 'post',
          url: url,
          data: {
            search: request.term,
            field: $(field).attr('name')
          },
          dataType: 'json',
          success: function(data) {
            return response(data);
          },
          error: function(answer) {
            return errorHandler(answer);
          }
        });
      },
      minLength: 2,
      select: function(event, ui) {
        return typeof selectCallback === "function" ? selectCallback(event, ui) : void 0;
      }
    });
  };

}).call(this);
