// Generated by CoffeeScript 2.4.1
(function() {
  $(document).on('click', '.close_notification', function() {
    var notification_id;
    notification_id = $(this).data('id');
    return $.ajax({
      type: 'post',
      url: '/notification',
      data: {
        id: notification_id,
        action: 'close_notification'
      },
      success: window.location.reload,
      error: function(answer) {
        return errorHandler(answer);
      }
    });
  });

  $(document).on('click', '.close_task', function() {
    var data, id, type;
    id = $(this).data('id');
    type = $(this).data('type');
    data = {
      id: id,
      type: type,
      action: 'close_form'
    };
    return $.ajax({
      type: 'post',
      url: '/task',
      data: data,
      success: function(answer) {
        return myModalOpen(answer);
      },
      error: function(answer) {
        return errorHandler(answer);
      }
    });
  });

  $(document).on('submit', '#close_task', function(event) {
    var data;
    event.preventDefault();
    data = $(this).serializeJSON();
    data.action = 'close';
    return $.ajax({
      type: 'post',
      url: '/task',
      data: data,
      success: function(answer) {
        return successHandler(answer);
      },
      error: function(answer) {
        return errorHandler(answer);
      }
    });
  });

}).call(this);
