// Generated by CoffeeScript 2.4.1
(function() {
  $(document).on('click', '#submit', function(event) {
    var login, password, remember_me;
    event.preventDefault();
    login = $('#login').val();
    password = $('#password').val();
    remember_me = $('#remember_me').is(':checked');
    return $.ajax({
      type: 'post',
      url: '/login',
      data: {login, password, remember_me},
      success: () => {
        if (window.location.pathname === '/login') {
          return window.location.href = '/';
        } else {
          return window.location.reload();
        }
      },
      error: (answer) => {
        return alert(answer.message);
      }
    });
  });

}).call(this);
