// Generated by CoffeeScript 2.4.1
(function() {
  var Modal;

  Modal = class Modal {
    constructor(html) {
      $('body').append(html);
      $('.modal').modal();
      this.handlers();
    }

    handlers() {
      $(document).on('click', '#modal_close', this.myModalClose);
      $(document).on('click', '.poster', this.myModalClose);
      return $(document).on('keydown', function() {
        return function(event) {
          if (event.which === 27) {
            return this.myModalClose();
          }
        };
      });
    }

    myModalClose() {
      $('.poster').css('z-index', '-1').animate({
        opacity: 0
      }, 400);
      $('#modal').css('z-index', '1').animate({
        opacity: 0
      }, 400);
      $('#content').css('display', 'block');
      $('#left_bar').css('display', 'block');
      return setTimeout(function() {
        return $('#modal').css('display', 'none', 400);
      });
    }

  };

}).call(this);
