// Generated by CoffeeScript 2.4.1
(function() {
  $(document).on('click', '.edit', function() {
    var data;
    data = {
      action: 'update',
      id: $(this).parents('tr').data('id')
    };
    $(this).parents('tr').find('.field').each(function() {
      return data[$(this).attr('name')] = $(this).val;
    });
    return $.ajax({
      type: 'post',
      url: url('/sms'),
      data: data,
      success: answer(function() {
        return successHandler(answer);
      }),
      error: answer(function() {
        return errorHandler(answer);
      })
    });
  });

}).call(this);
