// Generated by CoffeeScript 2.4.1
(function() {
  var add_margin, change_sum, filter_products;

  add_margin = function() {
    if ($('.search_combine_result').length > 0) {
      return $('.search_combine_result').css('margin-bottom', '15px');
    } else {
      return $('.search_combine_result').css('margin-bottom', '0px');
    }
  };

  change_sum = function() {
    var sum;
    sum = 0;
    $('.combine_products_item').each(function() {
      var amount, costs;
      amount = $(this).find('.amount').val();
      costs = $(this).find('.price').val();
      return sum += +costs * +amount;
    });
    $('[name="costs"]').val(sum);
    return add_margin();
  };

  $(document).on('input', '.combine_products_item input', change_sum);

  $(document).on('click', '.delete_combine_product', function() {
    $(this).parents('.combine_products_item').remove();
    return change_sum();
  });

  $(document).on('click', '#close_search_combine_result', function() {
    $('.search_combine_result').html('');
    return $('#search_products_to_combine').val('');
  });

  $(document).on('change', '[name="combine"]', function() {
    if ($(this).val()($('.combine_wrapper').show())) {

    } else {
      return $('.combine_wrapper').hide();
    }
  });

  $(document).on('keyup', '#search_products_to_combine', function() {
    var notIn, value;
    value = $(this).val();
    notIn = [];
    $('.combine_products_item').each(function() {
      return notIn.push($(this).data('id'));
    });
    return $.ajax({
      type: 'post',
      url: '/product',
      data: {
        value: value,
        action: 'search_products_to_combine',
        not: notIn
      },
      success: function(answer) {
        return $('.search_combine_result').html(answer);
      }
    });
  });

  $(document).on('click', '.get_product_to_combine', function(event) {
    var id;
    event.preventDefault();
    id = $this.data('id');
    return $.ajax({
      type: 'post',
      url: '/product',
      data: {
        id: id,
        action: 'get_product_to_combine'
      },
      success: (answer) => {
        $('.combine_products_list').prepend(answer);
        $(this).remove();
        return change_sum();
      }
    });
  });

  filter_products = function() {
    var data;
    data = {};
    $('[data-action=search]').each(function() {
      return data[$(this).data('column')] = $(this).val();
    });
    return GET.setObject(data).unset('page').unsetEmpty().go();
  };

  $(document).on('click', '#search', filter_products);

  $(document).on('keyup', '[data-action=search]', function(event) {
    if (event.which === 13) {
      return filter_products();
    }
  });

  $(document).on('change', 'select[data-action=search]', filter_products);

  $(document).on('click', '.sort', function(event) {
    event.preventDefault();
    return GET.set('order_field', $(this).data('field')).set('order_by', $(this).data('by')).go();
  });

  $(document).on('click', '.copy', function(event) {
    var amount;
    event.preventDefault();
    amount = prompt('Ведіть кількість копій!', '1');
    return $.ajax({
      type: 'post',
      url: '/product',
      data: {
        id: id,
        amount: amount,
        action: 'copy'
      },
      success: function(answer) {
        return successHandler(answer, function() {
          return window.location.href = '/product';
        });
      },
      error: function(answer) {
        return errorHandler(answer);
      }
    });
  });

  $(document).on('keyup', '#search_attribute', function() {
    var $this;
    $this = $(this);
    if ($this.val().length === 0 || $this.val() === '') {
      return $('.attribute_search_result').html('');
    }
    return $.ajax({
      type: 'post',
      url: '/product',
      data: {
        value: $this.val(),
        action: 'search_attribute'
      },
      success: function(answer) {
        return $('.attribute_search_result').html(answer);
      }
    });
  });

  $(document).on('click', '.get_searched_attribute', function(event) {
    var $this;
    event.preventDefault();
    $this = $(this);
    return $.ajax({
      type: 'post',
      url: '/product',
      data: {
        id: $this.data('id'),
        action: 'get_searched_attribute'
      },
      success: function(answer) {
        $('#attribute_list').prepend(answer);
        return $this.remove();
      },
      error: function(answer) {
        return errorHandler(answer);
      }
    });
  });

  $(document).on('click', '.delete_attribute_variant', function() {
    if ($(this).parents('.row').parent().find('.row').length > 2) {
      return $(this).parents('.row').remove();
    }
  });

  $(document).on('click', '.add_attribute_value', function(event) {
    var $clone, $input;
    event.preventDefault();
    $input = $(this).parents('.panel-body').find('.row').last();
    $clone = $input.clone(true, true);
    return $input.after($clone);
  });

  $(document).on('click', '.close_attribute_search_result', function() {
    $('.attribute_search_result').html('');
    return $('#search_attribute').val('');
  });

  $(document).on('click', '.delete_attribute', function() {
    return $(this).parents('.attribute_item').remove();
  });

  $(document).on('keyup', '[name="volume[]"]', function() {
    var sum;
    sum = 1;
    $('[name="volume[]"]').each(function() {
      return sum *= +$(this).val();
    });
    return $('#volume').val(sum / 1000000);
  });

  $(document).on('click', '.print_products', function() {
    var url;
    url = {};
    $('[data-action=search]').each(function() {
      return url[$(this).data('column')] = $(this).val();
    });
    url.section = 'print';
    GET.setObject(url).unsetEmpty().setDomain('/product').redirect();
    return $(this).blur();
  });

  $(document).on('click', '.pts_more', function() {
    var id;
    id = $(this).data('id');
    return $.ajax({
      type: 'post',
      url: 'product',
      data: {
        action: 'pts_more',
        id: id
      },
      success: function(answer) {
        return $('.pts_more_' + id).html(answer).show();
      }
    });
  });

  $(document).on('click', ':not(.pts_more_item)', function() {
    return $('.pts_more_item').hide();
  });

  $(document).on('click', '.more', function() {
    return $('.filters').toggleClass('none');
  });

  $(document).on('click', '.filters_ok', function() {
    return GET.set('items', $('[name=items]').val()).go();
  });

  $(document).on('click', '.print_tick', function() {
    var selected;
    selected = Elements.getCheckedValues('table', '.product_item');
    return GET.setObject({
      section: 'print_tick',
      ids: selected.toString()
    }).redirect();
  });

  $(document).on('click', '.print_stickers', function() {
    var selected;
    selected = Elements.getCheckedValues('table', '.product_item');
    return GET.setObject({
      section: 'print_stickers',
      ids: selected.toString()
    }).redirect();
  });

}).call(this);
