// Generated by CoffeeScript 2.4.1
(function() {
  $(document).on('keyup', '#phone', function() {
    return $('[name="client_id"]').remove();
  });

  $(document).on('keyup', '#fio', function() {
    var $this;
    $this = $(this);
    $('[name="client_id"]').remove;
    if ($this.val().length < 2) {
      return $.ajax({
        type: 'post',
        url: 'orders/search_clients',
        data: {
          fio: $this.val
        },
        success: answer(function() {
          return $('.search_clients').html(answer);
        }),
        error: answer(function() {
          return errorHandler(answer);
        })
      });
    } else {
      return $('.search_clients').html('');
    }
  });

  $(document).on('click', '.client', function() {
    var $this;
    $this = $(this);
    $('#create_order').prepend(`<input name='client_id' type='hidden' value='${$this.data('value')}'>`);
    $('#fio').val($this.text);
    $('#phone').val($this.data('phone'));
    return $('.search_clients').html('');
  });

}).call(this);
